# Generated by Django 4.2 on 2026-05-30 13:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '请输入有效的手机号')], verbose_name='手机号')),
                ('email_active', models.BooleanField(default=False, verbose_name='邮箱是否激活')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='昵称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
                'db_table': 'user_profile',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
